FROM node:latest
LABEL maintainer="Jose Francisco Alvarez Valdez<alvaresvaldes89@gmail.com>"
USER root
RUN apt update && apt install nano -y
RUN mkdir -p /home/node/app/src
WORKDIR /home/node/app
RUN mkdir node_modules
RUN chown -R node:node /home/node/app
COPY package*.json ./
COPY src/server.js src
RUN npm install
RUN npm install -g nodemon mocha
CMD ["nodemon", "src/server.js"]